name: Intro to GitHub Actions

on: 
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: build
        run: bun run build

      - name: run the server
        run: |
          bun run preview &
          sleep 5
          curl -I http://localhost:4173


